apiVersion: v1
kind: Service
metadata:
  name: cicd-demo
  namespace: dev
  labels:
    app: cicd-demo
spec:
  type: LoadBalancer
  selector:
    app: cicd-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: http
