apiVersion: v1
kind: Service
metadata:
  name: dcn-collector
  namespace: dcn
  labels:
    app: dcn-collector
spec:
  type: ClusterIP
  selector:
    app: dcn-collector
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: metrics
  clusterIP: None # Headless service for scraping
